### PR TITLE
Bump up eslint-plugin-react & react-hooks versions

### PR DESCRIPTION
**Pull request by yasincaliskan**
- `eslint-plugin-react` new version `7.23.1`,
- `eslint-plugin-react-hooks` new version `4.2.0`

### CODE REVIEW

**Review by bilgeyucel — COMMENTED** [review]
I am not sure if this is a major version update. I think it should be a minor version update

**Review by edizcelik — APPROVED** [review]

**Comment by edizcelik** [comment]
> I am not sure if this is a major version update. I think it should be a minor version update

Agreed. This should be a minor update as there aren't any breaking changes

**Comment by yasincaliskan** [comment]
Hmm, right! So, we can decide to minor or major version if there are breaking changes. Thank you!

**Review by Anlerkan — APPROVED** [review]

**Review by bilgeyucel — APPROVED** [review]

**Review by bilgeyucel — COMMENTED** [review]
Since these are the only updates we will make, you can update `package.json` version in this PR.

**Review by jamcry — APPROVED** [review]

**Review by bilgeyucel — APPROVED** [review]
🚀

**Pull request merged**
